apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-certificate-tls
  namespace: default
spec:
  secretName: my-certificate-tls
  subject:
    organizations:
      - my-org
  dnsNames:
    - my-certificate.svc
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
